// GENERATED by scripts/generate-content-index.mjs — do not edit.
import markets_ar from "./markets.ar.json";
import markets_de from "./markets.de.json";
import markets_es from "./markets.es.json";
import markets_fr from "./markets.fr.json";
import markets_it from "./markets.it.json";
import markets_ja from "./markets.ja.json";
import markets_nl from "./markets.nl.json";
import markets_pt from "./markets.pt.json";
import markets_zh_CN from "./markets.zh-CN.json";
import service_frameworks_ar from "./service-frameworks.ar.json";
import service_frameworks_de from "./service-frameworks.de.json";
import service_frameworks_es from "./service-frameworks.es.json";
import service_frameworks_fr from "./service-frameworks.fr.json";
import service_frameworks_it from "./service-frameworks.it.json";
import service_frameworks_ja from "./service-frameworks.ja.json";
import service_frameworks_nl from "./service-frameworks.nl.json";
import service_frameworks_pt from "./service-frameworks.pt.json";
import service_frameworks_zh_CN from "./service-frameworks.zh-CN.json";
import service_positioning_ar from "./service-positioning.ar.json";
import service_positioning_de from "./service-positioning.de.json";
import service_positioning_es from "./service-positioning.es.json";
import service_positioning_fr from "./service-positioning.fr.json";
import service_positioning_it from "./service-positioning.it.json";
import service_positioning_ja from "./service-positioning.ja.json";
import service_positioning_nl from "./service-positioning.nl.json";
import service_positioning_pt from "./service-positioning.pt.json";
import service_positioning_zh_CN from "./service-positioning.zh-CN.json";

export const translationFiles: Record<string, Record<string, unknown>> = {
  "markets": {
    "ar": markets_ar,
    "de": markets_de,
    "es": markets_es,
    "fr": markets_fr,
    "it": markets_it,
    "ja": markets_ja,
    "nl": markets_nl,
    "pt": markets_pt,
    "zh-CN": markets_zh_CN,
  },
  "service-frameworks": {
    "ar": service_frameworks_ar,
    "de": service_frameworks_de,
    "es": service_frameworks_es,
    "fr": service_frameworks_fr,
    "it": service_frameworks_it,
    "ja": service_frameworks_ja,
    "nl": service_frameworks_nl,
    "pt": service_frameworks_pt,
    "zh-CN": service_frameworks_zh_CN,
  },
  "service-positioning": {
    "ar": service_positioning_ar,
    "de": service_positioning_de,
    "es": service_positioning_es,
    "fr": service_positioning_fr,
    "it": service_positioning_it,
    "ja": service_positioning_ja,
    "nl": service_positioning_nl,
    "pt": service_positioning_pt,
    "zh-CN": service_positioning_zh_CN,
  },
};
