import { withSocial } from "../../../lib/seo";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { SiteHeader, SiteFooter } from "../../../components/SiteChrome";
import { languageAlternates, locales, type Locale } from "../../../data/i18n/locales";

type PrivacyCopy = { kicker: string; title: string; intro: string; updated: string; sections: [string, string][]; legalNote: string };
const copy: Record<Exclude<Locale, "en">, PrivacyCopy> = {
  es: { kicker: "Privacidad y cookies", title: "Cómo tratamos su información", intro: "Este aviso explica qué datos recogemos cuando se pone en contacto con nosotros a través de este sitio web, por qué los conservamos y qué puede pedirnos que hagamos con ellos.", updated: "Última actualización: 8 de octubre de 2026", legalNote: "Este aviso describe cómo tratamos la información recogida a través de este sitio web. No constituye asesoramiento jurídico ni forma parte de ningún contrato.", sections: [
    ["Quiénes somos", "Eunomia Pharma Services es un nombre comercial de Mivigilance Limited, responsable del tratamiento de los datos personales recogidos a través de este sitio web. Mivigilance Limited está registrada en Inglaterra y Gales con el número 12912269 y tiene su domicilio social en Rough Way, Heath House Road, Woking, GU22 0QU. Contacto: hello@eunomiapharmaservices.com o +44 7584 567018."],
    ["Qué datos recogemos", "Si completa el formulario de consulta o nos escribe por correo electrónico, recogemos los datos que decida facilitarnos: nombre, empresa, correo profesional, teléfono opcional y mensaje. No envíe datos de categorías especiales, información de pacientes ni notificaciones de acontecimientos adversos a través de este sitio. Para notificar un acontecimiento adverso, contacte directamente con el titular de la autorización de comercialización o con su autoridad reguladora nacional."],
    ["Por qué los conservamos y base jurídica", "Usamos estos datos para responder a su consulta, valorar si podemos ayudarle y continuar la conversación. Si se inicia una colaboración, usamos sus datos de contacto para prestar y administrar el trabajo. La base jurídica es nuestro interés legítimo en responder a consultas comerciales y gestionar la consultoría y, si se inicia una colaboración, la ejecución de un contrato."],
    ["Qué no hacemos", "No le añadimos a una lista de marketing por haber utilizado el formulario de contacto. No vendemos datos personales ni los compartimos fuera de Eunomia para el marketing de otra organización. Si se suscribe por separado a las novedades, puede retirar su consentimiento en cualquier momento."],
    ["Quién más accede a los datos", "Los datos personales están disponibles para el personal de Eunomia que los necesita para responder. Vercel procesa las consultas del sitio web y Resend las envía a nuestra bandeja de entrada. Cloudflare Turnstile realiza la comprobación de seguridad. Proveedores de servicios pueden tratar datos por nuestra cuenta y bajo condiciones escritas, incluidos proveedores de correo y alojamiento de documentos, el proveedor de alojamiento web y, si acepta recibir comunicaciones, la plataforma de email marketing. Actúan siguiendo nuestras instrucciones. Podemos revelar información si la ley lo exige o si es necesario para establecer o defender una reclamación legal."],
    ["Transferencias internacionales", "Algunos proveedores pueden tratar datos fuera del Reino Unido. En ese caso, nos basamos en las decisiones británicas de adecuación o en el Acuerdo o la Adenda de Transferencia Internacional de Datos del Reino Unido, junto con las salvaguardias adicionales necesarias."],
    ["Cuánto tiempo los conservamos", "Las consultas que no dan lugar a una colaboración se conservan hasta dos años y después se eliminan. Los registros de una colaboración se conservan durante su vigencia y seis años más, de acuerdo con nuestras obligaciones contractuales, fiscales y profesionales de conservación."],
    ["Sus derechos", "Conforme a la legislación británica de protección de datos, puede solicitar una copia de sus datos, su rectificación o eliminación, la limitación del tratamiento o la portabilidad, u oponerse al tratamiento basado en intereses legítimos. Escriba a hello@eunomiapharmaservices.com; responderemos en el plazo de un mes. También puede presentar una reclamación ante la Information Commissioner's Office (ICO) en ico.org.uk/make-a-complaint/ o llamar al 0303 123 1113. Agradeceríamos poder resolver primero cualquier problema."],
    ["Cookies", "Este sitio utiliza Ahrefs Web Analytics y Vercel Web Analytics sin cookies para comprender el uso agregado, las visitas y las fuentes de tráfico. Ahrefs también mide clics y envíos de formularios; no enviamos los valores de los campos de consulta como eventos analíticos. Los servicios externos, incluidos Google Fonts y los enlaces a recursos, tienen sus propios avisos de privacidad."],
    ["Cambios en este aviso", "Actualizamos este aviso cuando cambian nuestras prácticas. La fecha indicada arriba señala la última revisión."],
  ] },
  fr: { kicker: "Confidentialité et cookies", title: "Comment nous traitons vos informations", intro: "Cette notice explique quelles données nous recueillons lorsque vous nous contactez via ce site, pourquoi nous les conservons et ce que vous pouvez nous demander à leur sujet.", updated: "Dernière mise à jour : 8 octobre 2026", legalNote: "Cette notice décrit notre traitement des informations recueillies sur ce site. Elle ne constitue pas un conseil juridique et ne fait partie d’aucun contrat.", sections: [
    ["Qui sommes-nous ?", "Eunomia Pharma Services est le nom commercial de Mivigilance Limited, responsable du traitement des données personnelles recueillies sur ce site. Mivigilance Limited est immatriculée en Angleterre et au pays de Galles sous le numéro 12912269 ; son siège social se trouve à Rough Way, Heath House Road, Woking, GU22 0QU. Contact : hello@eunomiapharmaservices.com ou +44 7584 567018."],
    ["Quelles données recueillons-nous ?", "Si vous remplissez le formulaire de demande ou nous envoyez un e-mail, nous recueillons les informations que vous choisissez de fournir : nom, entreprise, adresse e-mail professionnelle, numéro de téléphone facultatif et message. N’envoyez pas de données de catégorie particulière, d’informations sur des patients ni de déclarations d’événements indésirables via ce site. Pour déclarer un événement indésirable, contactez directement le titulaire de l’autorisation de mise sur le marché ou votre autorité réglementaire nationale."],
    ["Pourquoi les conservons-nous et sur quelle base ?", "Nous utilisons ces informations pour répondre à votre demande, évaluer si nous pouvons vous aider et poursuivre la conversation. Si une mission est conclue, nous utilisons vos coordonnées pour réaliser et gérer le travail. Notre base juridique est notre intérêt légitime à répondre aux demandes professionnelles et à gérer notre activité de conseil et, lorsqu’une mission est conclue, l’exécution d’un contrat."],
    ["Ce que nous ne faisons pas", "Nous ne vous ajoutons pas à une liste marketing parce que vous avez utilisé le formulaire de contact. Nous ne vendons pas les données personnelles et ne les communiquons pas en dehors d’Eunomia pour le marketing d’une autre organisation. Si vous choisissez séparément de recevoir des actualités, vous pouvez retirer votre consentement à tout moment."],
    ["Qui d’autre y a accès ?", "Les données personnelles sont accessibles aux collègues d’Eunomia qui en ont besoin pour répondre. Vercel traite les demandes envoyées depuis le site et Resend les transmet à notre boîte de réception. Cloudflare Turnstile effectue le contrôle de sécurité. Des prestataires peuvent traiter des données pour notre compte dans le cadre d’accords écrits, notamment nos fournisseurs de messagerie et d’hébergement de documents, l’hébergeur du site et, si vous vous inscrivez, la plateforme d’e-mail marketing. Ils agissent selon nos instructions. Nous pouvons divulguer des informations si la loi l’exige ou si cela est nécessaire pour établir ou défendre une réclamation juridique."],
    ["Transferts internationaux", "Certains prestataires peuvent traiter des données en dehors du Royaume-Uni. Dans ce cas, nous nous appuyons sur les décisions britanniques d’adéquation ou sur l’Accord ou l’Addendum britannique de transfert international de données, ainsi que sur toute garantie supplémentaire nécessaire."],
    ["Durée de conservation", "Les demandes qui ne donnent pas lieu à une mission sont conservées jusqu’à deux ans, puis supprimées. Les dossiers de mission sont conservés pendant la mission et six ans après, conformément aux obligations contractuelles, fiscales et professionnelles de conservation."],
    ["Vos droits", "En vertu de la législation britannique sur la protection des données, vous pouvez demander une copie de vos données, leur rectification ou leur effacement, la limitation du traitement ou leur portabilité, ou vous opposer au traitement fondé sur l’intérêt légitime. Écrivez à hello@eunomiapharmaservices.com ; nous répondrons sous un mois. Vous pouvez également saisir l’Information Commissioner's Office (ICO) sur ico.org.uk/make-a-complaint/ ou appeler le 0303 123 1113. Nous vous serions reconnaissants de nous laisser d’abord la possibilité de régler le problème."],
    ["Cookies", "Ce site utilise Ahrefs Web Analytics et Vercel Web Analytics sans cookies pour comprendre l’usage agrégé, les pages vues et les sources de trafic. Ahrefs mesure aussi les clics et les envois de formulaires ; nous ne transmettons pas les valeurs des champs de demande comme événements analytiques. Les services externes, dont Google Fonts et les ressources liées, ont leurs propres notices de confidentialité."],
    ["Modifications de cette notice", "Nous mettons cette notice à jour lorsque nos pratiques changent. La date ci-dessus indique la date de sa dernière révision."],
  ] },
  de: { kicker: "Datenschutz und Cookies", title: "So gehen wir mit Ihren Informationen um", intro: "Dieser Hinweis erklärt, welche Daten wir erheben, wenn Sie uns über diese Website kontaktieren, warum wir sie speichern und was Sie diesbezüglich von uns verlangen können.", updated: "Zuletzt aktualisiert: 8. Oktober 2026", legalNote: "Dieser Hinweis beschreibt den Umgang mit Informationen, die über diese Website erhoben werden. Er ist keine Rechtsberatung und wird nicht Bestandteil eines Vertrags.", sections: [
    ["Wer wir sind", "Eunomia Pharma Services ist ein Handelsname der Mivigilance Limited, die für die über diese Website erhobenen personenbezogenen Daten verantwortlich ist. Mivigilance Limited ist in England und Wales unter der Unternehmensnummer 12912269 eingetragen. Der eingetragene Sitz befindet sich in Rough Way, Heath House Road, Woking, GU22 0QU. Kontakt: hello@eunomiapharmaservices.com oder +44 7584 567018."],
    ["Welche Daten wir erheben", "Wenn Sie das Anfrageformular ausfüllen oder uns eine E-Mail senden, erheben wir die Angaben, die Sie uns mitteilen möchten: Name, Unternehmen, geschäftliche E-Mail-Adresse, optionale Telefonnummer und Nachricht. Bitte übermitteln Sie über diese Website keine besonderen Kategorien personenbezogener Daten, Patienteninformationen oder Meldungen zu unerwünschten Ereignissen. Wenden Sie sich für solche Meldungen direkt an den Inhaber der Zulassung oder Ihre nationale Aufsichtsbehörde."],
    ["Warum und auf welcher Grundlage wir die Daten speichern", "Wir verwenden diese Angaben, um Ihre Anfrage zu beantworten, zu prüfen, ob wir helfen können, und das Gespräch fortzusetzen. Kommt eine Zusammenarbeit zustande, nutzen wir Ihre Kontaktdaten zur Erbringung und Verwaltung der Leistungen. Rechtsgrundlage ist unser berechtigtes Interesse an der Beantwortung geschäftlicher Anfragen und am Betrieb unserer Beratung sowie, bei einer Zusammenarbeit, die Vertragserfüllung."],
    ["Was wir nicht tun", "Wir nehmen Sie nicht in einen Marketingverteiler auf, nur weil Sie das Kontaktformular verwendet haben. Wir verkaufen personenbezogene Daten nicht und geben sie außerhalb von Eunomia nicht für das Marketing anderer Organisationen weiter. Wenn Sie sich gesondert für Neuigkeiten anmelden, können Sie Ihre Einwilligung jederzeit widerrufen."],
    ["Wer sonst Zugriff hat", "Personenbezogene Daten sind für Eunomia-Mitarbeitende zugänglich, die sie zur Beantwortung benötigen. Vercel verarbeitet Website-Anfragen; Resend leitet sie an unseren Posteingang weiter. Cloudflare Turnstile führt die Sicherheitsprüfung durch. Dienstleister können Daten auf unsere Weisung und auf Grundlage schriftlicher Vereinbarungen verarbeiten, darunter unsere Anbieter für E-Mail und Dokumentenspeicherung, der Website-Host und bei einer Anmeldung die E-Mail-Marketingplattform. Sie handeln nach unseren Weisungen. Wir können Informationen offenlegen, wenn dies gesetzlich vorgeschrieben oder zur Geltendmachung oder Verteidigung eines Rechtsanspruchs erforderlich ist."],
    ["Internationale Übermittlungen", "Einige Anbieter können Daten außerhalb des Vereinigten Königreichs verarbeiten. In diesem Fall stützen wir uns auf britische Angemessenheitsregelungen oder das britische International Data Transfer Agreement beziehungsweise den Addendum sowie gegebenenfalls zusätzliche Schutzmaßnahmen."],
    ["Wie lange wir Daten speichern", "Anfragen, aus denen keine Zusammenarbeit entsteht, speichern wir bis zu zwei Jahre und löschen sie anschließend. Unterlagen zu einer Zusammenarbeit speichern wir für deren Dauer und weitere sechs Jahre, entsprechend unseren vertraglichen, steuerlichen und beruflichen Aufbewahrungspflichten."],
    ["Ihre Rechte", "Nach britischem Datenschutzrecht können Sie eine Kopie Ihrer Daten, deren Berichtigung oder Löschung, eine Einschränkung der Verarbeitung oder Datenübertragbarkeit verlangen sowie einer Verarbeitung auf Grundlage berechtigter Interessen widersprechen. Schreiben Sie an hello@eunomiapharmaservices.com; wir antworten innerhalb eines Monats. Sie können sich außerdem bei der Information Commissioner's Office (ICO) unter ico.org.uk/make-a-complaint/ beschweren oder die Nummer 0303 123 1113 anrufen. Wir möchten die Gelegenheit erhalten, ein Anliegen zunächst selbst zu lösen."],
    ["Cookies", "Diese Website nutzt Ahrefs Web Analytics und Vercel Web Analytics ohne Cookies für aggregierte Nutzungsdaten, Seitenaufrufe und Zugriffsquellen. Ahrefs erfasst auch Klicks und Formularübermittlungen; wir senden keine Werte aus Anfragefeldern als Analyseereignisse. Externe Dienste wie Google Fonts und verlinkte Ressourcen haben eigene Datenschutzhinweise."],
    ["Änderungen dieses Hinweises", "Wir aktualisieren diesen Hinweis, wenn sich unsere Vorgehensweise ändert. Das oben angegebene Datum zeigt die letzte Überarbeitung."],
  ] },
  it: { kicker: "Privacy e cookie", title: "Come trattiamo le vostre informazioni", intro: "Questa informativa spiega quali dati raccogliamo quando ci contattate tramite questo sito, perché li conserviamo e cosa potete chiederci di fare con essi.", updated: "Ultimo aggiornamento: 8 ottobre 2026", legalNote: "Questa informativa descrive il trattamento delle informazioni raccolte tramite questo sito. Non costituisce consulenza legale e non fa parte di alcun contratto.", sections: [
    ["Chi siamo", "Eunomia Pharma Services è un nome commerciale di Mivigilance Limited, titolare del trattamento dei dati personali raccolti tramite questo sito. Mivigilance Limited è registrata in Inghilterra e Galles con numero societario 12912269 e ha sede legale presso Rough Way, Heath House Road, Woking, GU22 0QU. Contatti: hello@eunomiapharmaservices.com oppure +44 7584 567018."],
    ["Quali dati raccogliamo", "Se compilate il modulo di richiesta o ci scrivete via e-mail, raccogliamo i dati che scegliete di fornirci: nome, azienda, e-mail di lavoro, numero di telefono facoltativo e messaggio. Non inviate tramite questo sito dati appartenenti a categorie particolari, informazioni sui pazienti o segnalazioni di eventi avversi. Per segnalare un evento avverso, contattate direttamente il titolare dell’autorizzazione all’immissione in commercio o l’autorità regolatoria nazionale."],
    ["Perché li conserviamo e su quale base", "Utilizziamo questi dati per rispondere alla vostra richiesta, valutare se possiamo aiutarvi e proseguire la conversazione. Se inizia una collaborazione, utilizziamo i dati di contatto per svolgere e amministrare l’incarico. La base giuridica è il nostro legittimo interesse a rispondere alle richieste professionali e gestire la consulenza e, se inizia una collaborazione, l’esecuzione di un contratto."],
    ["Cosa non facciamo", "Non vi inseriamo in una lista di marketing perché avete usato il modulo di contatto. Non vendiamo i dati personali né li condividiamo al di fuori di Eunomia per il marketing di altre organizzazioni. Se scegliete separatamente di ricevere aggiornamenti, potete revocare il consenso in qualsiasi momento."],
    ["Chi altro può accedervi", "I dati personali sono accessibili ai colleghi di Eunomia che ne hanno bisogno per rispondere. Vercel tratta le richieste inviate tramite il sito e Resend le inoltra alla nostra casella di posta. Cloudflare Turnstile esegue il controllo di sicurezza. I fornitori di servizi possono trattare dati per nostro conto sulla base di accordi scritti, inclusi i fornitori di e-mail e archiviazione documenti, l’hosting del sito e, se vi iscrivete, la piattaforma di e-mail marketing. Agiscono secondo le nostre istruzioni. Possiamo divulgare informazioni se richiesto dalla legge o necessario per far valere o difendere un diritto."],
    ["Trasferimenti internazionali", "Alcuni fornitori possono trattare dati al di fuori del Regno Unito. In tal caso facciamo riferimento alle decisioni britanniche di adeguatezza o all’Accordo o Addendum britannico sul trasferimento internazionale dei dati, insieme alle ulteriori garanzie necessarie."],
    ["Per quanto tempo li conserviamo", "Le richieste che non portano a una collaborazione sono conservate fino a due anni e poi eliminate. I documenti relativi a una collaborazione sono conservati per la sua durata e per i sei anni successivi, in linea con gli obblighi contrattuali, fiscali e professionali di conservazione."],
    ["I vostri diritti", "Ai sensi della normativa britannica sulla protezione dei dati, potete chiedere una copia dei vostri dati, la rettifica o la cancellazione, la limitazione del trattamento o la portabilità, oppure opporvi al trattamento basato sul legittimo interesse. Scrivete a hello@eunomiapharmaservices.com; risponderemo entro un mese. Potete inoltre presentare un reclamo all’Information Commissioner's Office (ICO) su ico.org.uk/make-a-complaint/ o chiamare il numero 0303 123 1113. Vi saremmo grati di poter cercare prima di risolvere la questione."],
    ["Cookie", "Questo sito usa Ahrefs Web Analytics e Vercel Web Analytics senza cookie per comprendere utilizzo aggregato, visualizzazioni e fonti di traffico. Ahrefs misura anche clic e invii di moduli; non inviamo i valori dei campi delle richieste come eventi analitici. I servizi esterni, inclusi Google Fonts e le risorse collegate, hanno informative proprie."],
    ["Modifiche a questa informativa", "Aggiorniamo questa informativa quando cambiano le nostre prassi. La data sopra indica l’ultima revisione."],
  ] },
  pt: { kicker: "Privacidade e cookies", title: "Como tratamos as suas informações", intro: "Esta nota explica que dados recolhemos quando nos contacta através deste site, por que motivo os conservamos e o que nos pode pedir que façamos com eles.", updated: "Última atualização: 8 de outubro de 2026", legalNote: "Esta nota descreve o tratamento das informações recolhidas através deste site. Não constitui aconselhamento jurídico nem integra qualquer contrato.", sections: [
    ["Quem somos", "Eunomia Pharma Services é um nome comercial da Mivigilance Limited, responsável pelo tratamento dos dados pessoais recolhidos através deste site. A Mivigilance Limited está registada em Inglaterra e no País de Gales com o número de sociedade 12912269 e tem sede registada em Rough Way, Heath House Road, Woking, GU22 0QU. Contactos: hello@eunomiapharmaservices.com ou +44 7584 567018."],
    ["Que dados recolhemos", "Se preencher o formulário de contacto ou nos enviar um e-mail, recolhemos os dados que decidir fornecer: nome, empresa, e-mail profissional, número de telefone opcional e mensagem. Não envie através deste site dados de categorias especiais, informações de doentes nem notificações de acontecimentos adversos. Para notificar um acontecimento adverso, contacte diretamente o titular da autorização de introdução no mercado ou a autoridade reguladora nacional."],
    ["Por que os conservamos e com que fundamento", "Utilizamos estes dados para responder ao seu pedido, avaliar se podemos ajudar e dar continuidade à conversa. Se for iniciada uma colaboração, utilizamos os seus contactos para prestar e administrar o trabalho. O fundamento jurídico é o nosso interesse legítimo em responder a pedidos comerciais e gerir a consultoria e, se houver uma colaboração, a execução de um contrato."],
    ["O que não fazemos", "Não o incluímos numa lista de marketing por ter utilizado o formulário de contacto. Não vendemos dados pessoais nem os partilhamos fora da Eunomia para o marketing de outra organização. Se optar separadamente por receber atualizações, pode retirar o consentimento a qualquer momento."],
    ["Quem mais tem acesso", "Os dados pessoais são acessíveis aos colegas da Eunomia que deles necessitam para responder. A Vercel trata os pedidos enviados pelo site e a Resend envia-os para a nossa caixa de correio. O Cloudflare Turnstile realiza a verificação de segurança. Prestadores de serviços podem tratar dados por nossa conta ao abrigo de condições escritas, incluindo os fornecedores de e-mail e alojamento de documentos, o fornecedor do site e, se subscrever, a plataforma de e-mail marketing. Atuam segundo as nossas instruções. Podemos divulgar informações quando a lei o exigir ou quando for necessário para estabelecer ou defender uma reclamação jurídica."],
    ["Transferências internacionais", "Alguns fornecedores podem tratar dados fora do Reino Unido. Quando isso acontece, recorremos às decisões britânicas de adequação ou ao Acordo ou Adenda britânico de Transferência Internacional de Dados, juntamente com as salvaguardas adicionais necessárias."],
    ["Durante quanto tempo conservamos os dados", "Os pedidos que não originem uma colaboração são conservados até dois anos e depois eliminados. Os registos de uma colaboração são conservados durante o trabalho e nos seis anos seguintes, em conformidade com as obrigações contratuais, fiscais e profissionais de conservação."],
    ["Os seus direitos", "Ao abrigo da legislação britânica de proteção de dados, pode pedir uma cópia dos seus dados, a sua retificação ou eliminação, a limitação do tratamento ou a portabilidade, ou opor-se ao tratamento baseado em interesses legítimos. Escreva para hello@eunomiapharmaservices.com; responderemos no prazo de um mês. Pode também apresentar uma reclamação à Information Commissioner's Office (ICO) em ico.org.uk/make-a-complaint/ ou ligar para 0303 123 1113. Agradecemos que nos dê primeiro a oportunidade de resolver a questão."],
    ["Cookies", "Este site utiliza Ahrefs Web Analytics e Vercel Web Analytics sem cookies para compreender a utilização agregada, visualizações e fontes de tráfego. A Ahrefs também mede cliques e envios de formulários; não enviamos os valores dos campos de consulta como eventos analíticos. Serviços externos, incluindo Google Fonts e recursos ligados, têm os seus próprios avisos de privacidade."],
    ["Alterações a esta nota", "Atualizamos esta nota quando as nossas práticas mudam. A data acima indica a revisão mais recente."],
  ] },
  nl: { kicker: "Privacy en cookies", title: "Hoe we met uw gegevens omgaan", intro: "Deze kennisgeving legt uit welke gegevens we verzamelen wanneer u via deze website contact met ons opneemt, waarom we ze bewaren en wat u ons kunt vragen ermee te doen.", updated: "Laatst bijgewerkt: 8 oktober 2026", legalNote: "Deze kennisgeving beschrijft hoe we omgaan met informatie die via deze website is verzameld. Dit is geen juridisch advies en maakt geen deel uit van een overeenkomst.", sections: [
    ["Wie we zijn", "Eunomia Pharma Services is een handelsnaam van Mivigilance Limited, de verwerkingsverantwoordelijke voor persoonsgegevens die via deze website worden verzameld. Mivigilance Limited is geregistreerd in Engeland en Wales onder bedrijfsnummer 12912269. Het geregistreerde kantooradres is Rough Way, Heath House Road, Woking, GU22 0QU. Contact: hello@eunomiapharmaservices.com of +44 7584 567018."],
    ["Welke gegevens we verzamelen", "Als u het aanvraagformulier invult of ons e-mailt, verzamelen we de gegevens die u zelf verstrekt: uw naam en bedrijf, zakelijk e-mailadres, optioneel telefoonnummer en bericht. Stuur via deze website geen bijzondere persoonsgegevens, patiëntgegevens of meldingen van bijwerkingen. Neem voor een melding van een bijwerking rechtstreeks contact op met de houder van de handelsvergunning of uw nationale toezichthouder."],
    ["Waarom en op welke grond we gegevens bewaren", "We gebruiken deze gegevens om uw vraag te beantwoorden, te beoordelen of we kunnen helpen en het gesprek voort te zetten. Als er een opdracht volgt, gebruiken we uw contactgegevens om het werk uit te voeren en te beheren. De rechtsgrond is ons gerechtvaardigd belang bij het beantwoorden van zakelijke vragen en het uitvoeren van onze adviesactiviteiten en, bij een opdracht, de uitvoering van een overeenkomst."],
    ["Wat we niet doen", "We voegen u niet toe aan een marketinglijst omdat u het contactformulier hebt gebruikt. We verkopen geen persoonsgegevens en delen ze buiten Eunomia niet voor de marketing van een andere organisatie. Als u zich apart aanmeldt voor updates, kunt u uw toestemming op elk moment intrekken."],
    ["Wie er verder toegang heeft", "Persoonsgegevens zijn toegankelijk voor Eunomia-collega’s die ze nodig hebben om te reageren. Vercel verwerkt websiteaanvragen en Resend stuurt ze naar onze inbox. Cloudflare Turnstile voert de beveiligingscontrole uit. Dienstverleners kunnen namens ons gegevens verwerken op basis van schriftelijke voorwaarden, waaronder onze e-mail- en documentopslagproviders, de websitehost en, als u zich aanmeldt, het e-mailmarketingplatform. Zij volgen onze instructies. We kunnen informatie delen als de wet dat vereist of als dit nodig is om een juridische vordering in te stellen of te verdedigen."],
    ["Internationale doorgifte", "Sommige aanbieders kunnen gegevens buiten het Verenigd Koninkrijk verwerken. In dat geval baseren we ons op Britse adequaatheidsbesluiten of de Britse International Data Transfer Agreement of Addendum, samen met eventuele noodzakelijke aanvullende waarborgen."],
    ["Hoe lang we gegevens bewaren", "Aanvragen die niet tot een opdracht leiden, bewaren we maximaal twee jaar en verwijderen we daarna. Opdrachtdossiers bewaren we gedurende de opdracht en zes jaar daarna, overeenkomstig contractuele, fiscale en professionele bewaarplichten."],
    ["Uw rechten", "Op grond van de Britse privacywetgeving kunt u een kopie van uw gegevens, rectificatie of verwijdering, beperking of overdraagbaarheid vragen, of bezwaar maken tegen verwerking op basis van gerechtvaardigde belangen. Mail hello@eunomiapharmaservices.com; we reageren binnen een maand. U kunt ook een klacht indienen bij de Information Commissioner's Office (ICO) via ico.org.uk/make-a-complaint/ of bellen naar 0303 123 1113. We stellen het op prijs als we eerst de kans krijgen om het probleem op te lossen."],
    ["Cookies", "Deze website gebruikt Ahrefs Web Analytics en Vercel Web Analytics zonder cookies voor geaggregeerd gebruik, paginaweergaven en verkeersbronnen. Ahrefs meet ook klikken en formulierinzendingen; wij versturen geen waarden uit aanvraagvelden als analysegebeurtenissen. Externe diensten, waaronder Google Fonts en gekoppelde bronnen, hebben eigen privacyverklaringen."],
    ["Wijzigingen in deze kennisgeving", "We passen deze kennisgeving aan wanneer onze werkwijze verandert. De datum hierboven geeft aan wanneer deze voor het laatst is herzien."],
  ] },
  ja: { kicker: "プライバシーとCookie", title: "お客様の情報の取り扱い", intro: "本通知では、このウェブサイトからお問い合わせいただいた際に収集する情報、その利用・保管の理由、お客様が求めることのできる対応について説明します。", updated: "最終更新日：2026年10月8日", legalNote: "本通知は、このウェブサイトを通じて収集した情報の取り扱いについて説明するものです。法的助言ではなく、契約の一部を構成するものでもありません。", sections: [
    ["運営者", "Eunomia Pharma Servicesは、このウェブサイトを通じて収集する個人データの管理者であるMivigilance Limitedの事業名です。Mivigilance Limitedはイングランドおよびウェールズで会社番号12912269として登録されており、登記住所はRough Way, Heath House Road, Woking, GU22 0QUです。連絡先：hello@eunomiapharmaservices.com または +44 7584 567018。"],
    ["収集する情報", "お問い合わせフォームへの入力またはメールで、お客様が提供を選択した氏名、会社名、勤務先メールアドレス、任意の電話番号、メッセージを収集します。このサイトから、特別カテゴリーの個人データ、患者情報、有害事象報告を送信しないでください。有害事象の報告は、製造販売承認取得者または各国の規制当局に直接ご連絡ください。"],
    ["利用・保管の理由と法的根拠", "お問い合わせへの回答、支援の可否の判断、やり取りの継続に情報を利用します。業務の依頼につながった場合は、連絡先を業務の提供と管理に使用します。法的根拠は、事業上の問い合わせへの回答およびコンサルティング事業の運営に関する正当な利益であり、業務の依頼が成立した場合は契約の履行です。"],
    ["行わないこと", "お問い合わせフォームを利用したことを理由に、マーケティングリストへ追加することはありません。個人データを販売したり、他社のマーケティング目的でEunomiaの外部に共有したりしません。別途ニュースの配信に登録した場合も、いつでも同意を撤回できます。"],
    ["第三者のアクセス", "個人データは、お問い合わせへの回答に必要なEunomiaの担当者が利用します。ウェブサイトへのお問い合わせはVercelが処理し、Resendを通じて当社の受信箱へ送信されます。セキュリティ確認にはCloudflare Turnstileを使用します。メール・文書保管の提供者、サイトホスティング事業者、登録した場合のメールマーケティング事業者などの委託先は、書面による条件と当社の指示に従ってデータを処理することがあります。法律上必要な場合、または法的請求の提起・防御に必要な場合、情報を開示することがあります。"],
    ["国外移転", "一部の委託先は英国外でデータを処理する場合があります。その場合、英国の十分性認定または国際データ移転契約・補遺に依拠し、必要な追加保護措置も講じます。"],
    ["保管期間", "業務の依頼につながらなかったお問い合わせは最長2年間保管した後、削除します。業務記録は契約期間中および終了後6年間保管します。これは契約、税務、専門上の記録保管義務に沿ったものです。"],
    ["お客様の権利", "英国のデータ保護法に基づき、データの写し、訂正・削除、処理の制限、データポータビリティを請求できます。また、正当な利益に基づく処理に異議を申し立てることもできます。hello@eunomiapharmaservices.com までご連絡ください。1か月以内に回答します。Information Commissioner's Office（ICO）へ ico.org.uk/make-a-complaint/ から苦情を申し立てるか、0303 123 1113へ電話することもできます。まず当社が問題を解決する機会をいただければ幸いです。"],
    ["Cookie", "このサイトは、Cookieを使わないAhrefs Web AnalyticsとVercel Web Analyticsで、集計された利用状況、ページ閲覧、流入元を把握します。Ahrefsはクリックやフォーム送信も計測しますが、お問い合わせ入力欄の値を分析イベントとして送信しません。Google Fontsやリンク先の資料など、外部サービスには独自のプライバシー通知が適用されます。"],
    ["本通知の変更", "取り扱い方法が変わった場合、本通知を更新します。上記の日付は最終更新日です。"],
  ] },
  "zh-CN": { kicker: "隐私与 Cookie", title: "我们如何处理您的信息", intro: "本隐私声明说明您通过本网站联系我们时，我们会收集哪些信息、为何保留这些信息，以及您可以要求我们如何处理这些信息。", updated: "最后更新：2026 年 10 月 8 日", legalNote: "本声明说明我们如何处理通过本网站收集的信息，不构成法律意见，也不构成任何合同的一部分。", sections: [
    ["关于我们", "Eunomia Pharma Services 是 Mivigilance Limited 的商业名称。Mivigilance Limited 是通过本网站收集的个人数据的数据控制者，在英格兰和威尔士注册，公司编号 12912269，注册地址为 Rough Way, Heath House Road, Woking, GU22 0QU。联系方式：hello@eunomiapharmaservices.com 或 +44 7584 567018。"],
    ["我们收集的信息", "如果您填写咨询表或给我们发送电子邮件，我们会收集您选择提供的信息：姓名、公司、工作邮箱、可选电话号码和留言。请勿通过本网站发送特殊类别个人数据、患者信息或不良事件报告。如需报告不良事件，请直接联系上市许可持有人或您所在国家/地区的监管机构。"],
    ["收集目的和法律依据", "我们使用这些信息回复您的咨询、评估是否能够提供帮助并继续沟通。如果后续建立合作关系，我们会使用您的联系方式提供和管理相关工作。法律依据是我们为回复商业咨询和运营咨询业务而享有的合法利益；如建立合作关系，则依据是履行合同。"],
    ["我们不会做什么", "您使用联系表后，我们不会因此将您加入营销名单。我们不会出售个人数据，也不会在 Eunomia 之外为其他组织的营销目的共享个人数据。如果您另行选择订阅资讯，可以随时撤回同意。"],
    ["其他可访问信息的主体", "有需要处理咨询的 Eunomia 同事可以访问个人数据。网站咨询由 Vercel 处理，并通过 Resend 发送到我们的收件箱。Cloudflare Turnstile 执行安全验证。服务提供商可依据书面条款代表我们处理数据，包括电子邮件和文档托管服务商、网站托管商，以及在您选择订阅时使用的电子邮件营销平台。他们按照我们的指示行事。在法律要求或为提出、维护或抗辩法律主张所必需时，我们可能披露信息。"],
    ["国际传输", "部分服务提供商可能在英国境外处理数据。在这种情况下，我们依据英国充分性决定或英国《国际数据传输协议》或附录，并采取所需的额外保障措施。"],
    ["保留期限", "未转为合作的咨询最多保留两年，之后删除。合作记录在合作期间及其后六年内保留，以符合合同、税务和专业记录保存义务。"],
    ["您的权利", "根据英国数据保护法，您可以要求获取数据副本、更正或删除数据、限制处理或转移数据，也可以反对基于合法利益的处理。请发送邮件至 hello@eunomiapharmaservices.com；我们会在一个月内回复。您也可以通过 ico.org.uk/make-a-complaint/ 向 Information Commissioner's Office（ICO）投诉，或拨打 0303 123 1113。我们希望先有机会处理并解决您的问题。"],
    ["Cookie", "本网站使用不依赖Cookie的Ahrefs Web Analytics和Vercel Web Analytics，了解汇总的网站使用情况、页面浏览量和流量来源。Ahrefs也统计点击和表单提交；我们不会将咨询表单字段值作为分析事件发送。Google Fonts和链接资源等外部服务适用各自的隐私声明。"],
    ["本声明的变更", "我们的做法发生变化时，会更新本声明。上方日期显示本声明最近一次修订的时间。"],
  ] },
  ar: { kicker: "الخصوصية وملفات تعريف الارتباط", title: "كيف نتعامل مع معلوماتكم", intro: "توضح هذه الإشعار البيانات التي نجمعها عند تواصلكم معنا عبر هذا الموقع، وأسباب الاحتفاظ بها، وما يمكنكم طلبه منا بشأنها.", updated: "آخر تحديث: 8 أكتوبر 2026", legalNote: "يوضح هذا الإشعار كيفية تعاملنا مع المعلومات التي تُجمع عبر هذا الموقع. ولا يُعد مشورة قانونية أو جزءاً من أي عقد.", sections: [
    ["من نحن", "Eunomia Pharma Services هو اسم تجاري لشركة Mivigilance Limited، وهي الجهة المتحكمة في البيانات الشخصية التي تُجمع عبر هذا الموقع. الشركة مسجلة في إنجلترا وويلز برقم 12912269، وعنوان مكتبها المسجل Rough Way, Heath House Road, Woking, GU22 0QU. للتواصل: hello@eunomiapharmaservices.com أو +44 7584 567018."],
    ["ما البيانات التي نجمعها", "إذا ملأتم نموذج الاستفسار أو راسلتمونا بالبريد الإلكتروني، نجمع التفاصيل التي تختارون تقديمها: الاسم واسم الشركة والبريد الإلكتروني للعمل ورقم هاتف اختياري والرسالة. يُرجى عدم إرسال بيانات من فئات خاصة أو معلومات المرضى أو بلاغات الأحداث الضارة عبر هذا الموقع. للإبلاغ عن حدث ضار، تواصلوا مباشرة مع صاحب ترخيص التسويق أو الجهة التنظيمية الوطنية."],
    ["لماذا نحتفظ بها وما الأساس القانوني", "نستخدم هذه التفاصيل للرد على استفساركم وتقييم إمكانية مساعدتكم ومواصلة التواصل. وإذا بدأ تكليف، نستخدم بيانات الاتصال لتقديم العمل وإدارته. الأساس القانوني هو مصلحتنا المشروعة في الرد على استفسارات الأعمال وإدارة خدماتنا الاستشارية، وعند بدء التكليف يكون الأساس تنفيذ العقد."],
    ["ما الذي لا نفعله", "لا نضيفكم إلى قائمة تسويقية لمجرد استخدام نموذج التواصل. لا نبيع البيانات الشخصية ولا نشاركها خارج Eunomia لأغراض التسويق لمنظمة أخرى. إذا اشتركتم بشكل منفصل لتلقي التحديثات، يمكنكم سحب موافقتكم في أي وقت."],
    ["من يمكنه الاطلاع عليها أيضاً", "تتاح البيانات الشخصية لزملاء Eunomia الذين يحتاجون إليها للرد. تعالج Vercel استفسارات الموقع وترسلها Resend إلى صندوق بريدنا. يجري Cloudflare Turnstile فحص الأمان. قد يعالج مقدمو الخدمات البيانات نيابة عنا بموجب شروط مكتوبة، ومنهم مزودو البريد الإلكتروني واستضافة المستندات ومضيف الموقع ومنصة التسويق عبر البريد الإلكتروني عند الاشتراك فيها. يعملون وفق تعليماتنا. وقد نفصح عن المعلومات إذا أوجب القانون ذلك أو لزم لإقامة مطالبة قانونية أو الدفاع عنها."],
    ["النقل الدولي", "قد يعالج بعض مقدمي الخدمات البيانات خارج المملكة المتحدة. عندئذ نعتمد على قرارات الملاءمة البريطانية أو اتفاقية نقل البيانات الدولية البريطانية أو ملحقها، إلى جانب أي ضمانات إضافية لازمة."],
    ["مدة الاحتفاظ", "نحتفظ بالاستفسارات التي لا تتحول إلى تكليف لمدة تصل إلى عامين ثم نحذفها. ونحتفظ بسجلات التكليف طوال مدته ولمدة ست سنوات بعده، وفقاً لالتزاماتنا التعاقدية والضريبية والمهنية بحفظ السجلات."],
    ["حقوقكم", "بموجب قانون حماية البيانات البريطاني، يمكنكم طلب نسخة من بياناتكم أو تصحيحها أو حذفها أو تقييد معالجتها أو نقلها، كما يمكنكم الاعتراض على المعالجة القائمة على المصلحة المشروعة. راسلونا على hello@eunomiapharmaservices.com وسنرد خلال شهر. ويمكنكم أيضاً تقديم شكوى إلى Information Commissioner's Office (ICO) عبر ico.org.uk/make-a-complaint/ أو الاتصال على 0303 123 1113. نرحب بمنحنا فرصة معالجة المسألة أولاً."],
    ["ملفات تعريف الارتباط", "يستخدم الموقع Ahrefs Web Analytics وVercel Web Analytics دون ملفات تعريف ارتباط لفهم الاستخدام المجمع ومشاهدات الصفحات ومصادر الزيارات. تقيس Ahrefs أيضاً النقرات وإرسال النماذج؛ ولا نرسل قيم حقول الاستفسارات كأحداث تحليلية. للخدمات الخارجية، بما فيها Google Fonts والموارد المرتبطة، إشعارات خصوصية خاصة بها."],
    ["التغييرات على هذا الإشعار", "نحدّث هذا الإشعار عند تغيّر ممارساتنا. ويبيّن التاريخ أعلاه آخر مراجعة له."],
  ] },
};

export function generateStaticParams() {
  return (Object.keys(locales) as Locale[]).filter((locale) => locale !== "en").map((locale) => ({ locale }));
}

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!Object.prototype.hasOwnProperty.call(copy, locale)) return {};
  const text = copy[locale as Exclude<Locale, "en">];
  return withSocial(`/${locale}/privacy`, {
    title: `${text.kicker} | Eunomia Pharma Services`,
    description: text.intro,
    alternates: {
      canonical: `https://www.eunomiapharmaservices.com/${locale}/privacy`,
      languages: languageAlternates("/privacy"),
    },
  });
}

export default async function LocalizedPrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!Object.prototype.hasOwnProperty.call(copy, locale)) notFound();
  const selected = locale as Exclude<Locale, "en">;
  const text = copy[selected];
  return (
    <main lang={selected} dir={locales[selected].dir}>
      <SiteHeader locale={selected} />
      <section className="privacy-hero section-pad">
        <p className="section-kicker">{text.kicker}</p>
        <h1>{text.title}</h1>
        <p>{text.intro}</p>
        <small>{text.updated}</small>
      </section>
      <section className="privacy-content section-pad">
        {text.sections.map(([title, body]) => (
          <section key={title}>
            <h2>{title}</h2>
            <p>{body}</p>
          </section>
        ))}
        <p className="legal-note">{text.legalNote}</p>
      </section>
      <SiteFooter locale={selected} />
    </main>
  );
}
